# Automapper configuration
# [templates.example_template] - example_template should be replaced with the name of your map template.
# directory - The direct path to our map files.
# map_files - These are the names of the map files, including the extension, that will be loaded. Supports multiple for randomness.
# required_map - This is the name of the required map that needs to be loaded in order for this template to load.
# coordinates - The coordinates of the map template placement. (X, Y, Z). PLEASE NOTE: The Z coordinate is the same as would be shown in SDMM. NOT IN GAME.
# leave it at 1 if it is not a multi-z map. It is relative to the map file Z, not the one loaded in game.
# trait_name - The name of the Z level trait that will be used to determine what Z level we use.
# Traits - Station (for station relatied edits), CentCom (for edits on the CC map), Mining (for edits on Lavaland)
# More can be found in code\__DEFINES\maps.dm

# METASTATION MAP TEMPLATES
# Metastation Interlink
[templates.metastation_interlink]
map_files = ["metastation_interlink.dmm"]
directory = "_maps/effigy/templates/automapper/metastation/"
required_map = "MetaStation.dmm"
coordinates = [50, 128, 1]
trait_name = "Station"

# Metastation Cryo
[templates.metastation_cryo]
map_files = ["metastation_cryo.dmm"]
directory = "_maps/effigy/templates/automapper/metastation/"
required_map = "MetaStation.dmm"
coordinates = [136, 182, 1]
trait_name = "Station"

# ICEBOX MAP TEMPLATES
# Icebox Interlink
[templates.icebox_interlink]
map_files = ["icebox_interlink.dmm"]
directory = "_maps/effigy/templates/automapper/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [33, 132, 3]
trait_name = "Station"

# Icebox Cryo
[templates.icebox_cryo]
map_files = ["icebox_cryo.dmm"]
directory = "_maps/effigy/templates/automapper/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [117, 142, 3]
trait_name = "Station"

# Icebox Pool Surface
[templates.icebox_pool_surface]
map_files = ["icebox_pool_surface.dmm"]
directory = "_maps/effigy/templates/automapper/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [134, 149, 3]
trait_name = "Station"

# Icebox Pool Caves
[templates.icebox_pool_underground]
map_files = ["icebox_pool_underground.dmm"]
directory = "_maps/effigy/templates/automapper/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [128, 149, 2]
trait_name = "Station"

# TRAMSTATION MAP TEMPLATES
# Tramstation Cryo
[templates.tramstation_cryo]
map_files = ["tramstation_cryo.dmm"]
directory = "_maps/effigy/templates/automapper/tramstation/"
required_map = "tramstation.dmm"
coordinates = [68, 102, 2]
trait_name = "Station"

# Tramstation Interlink
[templates.tramstation_interlink]
map_files = ["tramstation_interlink.dmm"]
directory = "_maps/effigy/templates/automapper/tramstation/"
required_map = "tramstation.dmm"
coordinates = [42, 114, 2]
trait_name = "Station"
