/datum/design/borg_suit
	name = "Cybernetic Endoskeleton"

/datum/design/borg_chest
	name = "Basic Torso"
	category = list(
		RND_CATEGORY_MECHFAB_CYBORG + RND_SUBCATEGORY_MECHFAB_CYBORG_CHASSIS,
		RND_CATEGORY_CYBERNETICS + RND_SUBCATEGORY_CYBERNETICS_BASIC_LIMBS,
	)

/datum/design/borg_head
	name = "Basic Head"
	category = list(
		RND_CATEGORY_MECHFAB_CYBORG + RND_SUBCATEGORY_MECHFAB_CYBORG_CHASSIS,
		RND_CATEGORY_CYBERNETICS + RND_SUBCATEGORY_CYBERNETICS_BASIC_LIMBS,
	)

/datum/design/borg_l_arm
	name = "Basic Left Arm"
	category = list(
		RND_CATEGORY_MECHFAB_CYBORG + RND_SUBCATEGORY_MECHFAB_CYBORG_CHASSIS,
		RND_CATEGORY_CYBERNETICS + RND_SUBCATEGORY_CYBERNETICS_BASIC_LIMBS,
	)

/datum/design/borg_r_arm
	name = "Basic Right Arm"
	category = list(
		RND_CATEGORY_MECHFAB_CYBORG + RND_SUBCATEGORY_MECHFAB_CYBORG_CHASSIS,
		RND_CATEGORY_CYBERNETICS + RND_SUBCATEGORY_CYBERNETICS_BASIC_LIMBS,
	)

/datum/design/borg_l_leg
	name = "Basic Left Leg"
	category = list(
		RND_CATEGORY_MECHFAB_CYBORG + RND_SUBCATEGORY_MECHFAB_CYBORG_CHASSIS,
		RND_CATEGORY_CYBERNETICS + RND_SUBCATEGORY_CYBERNETICS_BASIC_LIMBS,
	)

/datum/design/borg_r_leg
	name = "Basic Right Leg"
	category = list(
		RND_CATEGORY_MECHFAB_CYBORG + RND_SUBCATEGORY_MECHFAB_CYBORG_CHASSIS,
		RND_CATEGORY_CYBERNETICS + RND_SUBCATEGORY_CYBERNETICS_BASIC_LIMBS,
	)
