DEFINE_BITFIELD(biological_state, list(
	"BIO_INORGANIC" = BIO_INORGANIC,
	"BIO_BONE" = BIO_BONE,
	"BIO_FLESH" = BIO_FLESH,
	"BIO_METAL" = BIO_METAL,
	"BIO_WIRED" = BIO_WIRED,
	"BIO_BLOODED" = BIO_BLOODED,
	"BIO_JOINTED" = BIO_JOINTED,
))
